apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksclusters.aws.platform.example.org
spec:
  group: aws.platform.example.org
  names:
    kind: XEKSCluster
    plural: xeksclusters
  claimNames:
    kind: EKSCluster
    plural: eksclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    clusterVersion:
                      type: string
                    region:
                      type: string
                    nodeSize:
                      type: string
                    nodeCount:
                      type: integer
                  required:
                    - region
              required:
                - parameters