apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksclusters.aws.platform.example.org
spec:
  group: aws.platform.example.org
  names:
    kind: XEKSCluster
    plural: xeksclusters
  claimNames:
    kind: EKSCluster
    plural: eksclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    clusterVersion:
                      type: string
                      description: "EKS cluster version (e.g. 1.28)"
                      default: "1.28"
                    region:
                      type: string
                      description: "AWS region"
                      default: "us-west-2"
                    nodeSize:
                      type: string
                      description: "EC2 instance type for worker nodes"
                      default: "t3.medium"
                    nodeCount:
                      type: integer
                      description: "Number of worker nodes"
                      default: 2
                  required:
                    - region
              required:
                - parameters