apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.aws.platform.example.org
spec:
  group: aws.platform.example.org 
  names:
    kind: XVPC
    plural: xvpcs
  claimNames:
    kind: VPCClaim
    plural: vpcclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                  default: eu-north-1
                cidrBlock:
                  type: string
                  default: 10.0.0.0/16
                availabilityZones:
                  type: array
                  items:
                    type: string
                  default: ["eu-north-1a", "eu-north-1b"]
              required:
                - region
                - cidrBlock
                - availabilityZones