apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-crossplane-extensions-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/devplatformsolutions/platform-crossplane-extensions.git'
    path: 'orgs/devplatform.io'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true