apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - aws-provider.yaml
- ec2-provider.yaml
- dynamodb-provider.yaml
- s3-provider.yaml
- eks-provider.yaml
- iam-provider.yaml
- kms-provider.yaml