apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc.aws.platform.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: aws.platform.example.org/v1alpha1
    kind: XVPC
  resources:
    # VPC
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        metadata:
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            cidrBlock: 10.0.0.0/16
            enableDnsSupport: true
            enableDnsHostnames: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Internet Gateway
    - name: internet-gateway
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: InternetGateway
        metadata:
          name: my-igw
          annotations:
            crossplane.io/external-name: my-igw
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Public Subnets
    - name: public-subnet-1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          name: public-subnet-1
          annotations:
            crossplane.io/external-name: public-subnet-1
          labels:
            provider: aws
            subnet-type: public
        spec:
          forProvider:
            region: us-east-1
            cidrBlock: 10.0.1.0/24
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: us-east-1a
            mapPublicIpOnLaunch: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: public-subnet-2
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          name: public-subnet-2
          annotations:
            crossplane.io/external-name: public-subnet-2
          labels:
            provider: aws
            subnet-type: public
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            cidrBlock: 10.0.2.0/24
            availabilityZone: us-east-1b
            mapPublicIpOnLaunch: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: public-subnet-3
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          name: public-subnet-3
          annotations:
            crossplane.io/external-name: public-subnet-3
          labels:
            provider: aws
            subnet-type: public
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            cidrBlock: 10.0.3.0/24
            availabilityZone: us-east-1c
            mapPublicIpOnLaunch: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # NAT Gateway
    - name: nat-gateway
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: NATGateway
        metadata:
          name: main-nat
          annotations:
            crossplane.io/external-name: main-nat
          labels:
            provider: aws
        spec:
          forProvider:
            connectivityType: public 
            region: us-east-1
            subnetIdSelector:
              matchControllerRef: true
            allocationSelector:
              matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: nat-eip
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: EIP
        metadata:
          name: nat-eip
          # annotations:
          #   crossplane.io/external-name: nat-eip
        spec:
          forProvider:
            region: us-east-1
            domain: 'vpc'
            # publicIpv4Pool: identifier
            # vpc: false
          managementPolicies: 
            - "*"

    # Public Route Table
    - name: public-route-table
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        metadata:
          name: public-rt
          annotations:
            crossplane.io/external-name: public-rt
          labels:
            provider: aws
            table-type: public
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - cidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Public Route Table Associations
    - name: public-subnet-1-association
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        metadata:
          name: public-subnet-1-association
          annotations:
            crossplane.io/external-name: public-subnet-1-association
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                subnet-type: public
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                table-type: public
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: public-subnet-2-association
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        metadata:
          name: public-subnet-2-association
          annotations:
            crossplane.io/external-name: public-subnet-2-association
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                subnet-type: public
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                table-type: public
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: public-subnet-3-association
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        metadata:
          name: public-subnet-3-association
          annotations:
            crossplane.io/external-name: public-subnet-3-association
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                subnet-type: public
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                table-type: public
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
    # Private Subnets
    - name: private-subnet-1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          name: private-subnet-1
          annotations:
            crossplane.io/external-name: private-subnet-1
          labels:
            provider: aws
            subnet-type: private
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            cidrBlock: 10.0.10.0/24
            availabilityZone: us-east-1a
            mapPublicIpOnLaunch: false
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: private-subnet-2
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          name: private-subnet-2
          annotations:
            crossplane.io/external-name: private-subnet-2
          labels:
            provider: aws
            subnet-type: private
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            cidrBlock: 10.0.11.0/24
            availabilityZone: us-east-1b
            mapPublicIpOnLaunch: false
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: private-subnet-3
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        metadata:
          name: private-subnet-3
          annotations:
            crossplane.io/external-name: private-subnet-3
          labels:
            provider: aws
            subnet-type: private
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            cidrBlock: 10.0.12.0/24
            availabilityZone: us-east-1c
            mapPublicIpOnLaunch: false
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Private Route Table
    - name: private-route-table
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        metadata:
          name: private-rt
          annotations:
            crossplane.io/external-name: private-rt
          labels:
            provider: aws
            table-type: private
        spec:
          forProvider:
            region: us-east-1
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - cidrBlock: 0.0.0.0/0
                natGatewayIdSelector:
                  matchControllerRef: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    # Private Route Table Associations
    - name: private-subnet-1-association
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        metadata:
          name: private-subnet-1-association
          annotations:
            crossplane.io/external-name: private-subnet-1-association
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                subnet-type: private
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                table-type: private
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: private-subnet-2-association
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        metadata:
          name: private-subnet-2-association
          annotations:
            crossplane.io/external-name: private-subnet-2-association
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                subnet-type: private
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                table-type: private
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region

    - name: private-subnet-3-association
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTableAssociation
        metadata:
          name: private-subnet-3-association
          annotations:
            crossplane.io/external-name: private-subnet-3-association
          labels:
            provider: aws
        spec:
          forProvider:
            region: us-east-1
            subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                subnet-type: private
            routeTableIdSelector:
              matchControllerRef: true
              matchLabels:
                table-type: private
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region