apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc.aws.platform.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: aws.platform.example.org/v1alpha1
    kind: XVPC
  resources:
    # VPC
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            region: eu-north-1
            cidrBlock: 10.0.0.0/16
            enableDnsHostnames: true
            enableDnsSupport: true
            tags:
              - key: Name
                value: EksClusterStack/EksCluster/DefaultVpc
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.cidrBlock
          toFieldPath: spec.forProvider.cidrBlock

    # Internet Gateway
    - name: igw
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            region: eu-north-1
            tags:
              - key: Name
                value: EksClusterStack/EksCluster/DefaultVpc
            vpcIdRef:
              name: vpc
      dependsOn:
        - vpc
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    # Public Subnet 1
    - name: public-subnet-1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            region: eu-north-1
            availabilityZone: eu-north-1a
            cidrBlock: 10.0.0.0/19
            mapPublicIpOnLaunch: true
            vpcIdRef:
              name: vpc
            tags:
              - key: Name
                value: PublicSubnet
              - key: kubernetes.io/cluster/EksCluster
                value: shared
      dependsOn:
        - vpc
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    # Public Route Table 1
    - name: public-route-table-1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: eu-north-1
            vpcIdRef:
              name: vpc
            routes:
              - cidrBlock: 0.0.0.0/0
                gatewayIdRef:
                  name: igw
            tags:
              - key: Name
                value: PublicSubnet
      dependsOn:
        - igw
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    # NAT Gateway Resources
    - name: nat-eip
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: EIP
        spec:
          forProvider:
            region: eu-north-1
            domain: vpc
      dependsOn:
        - vpc
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    - name: nat-gateway
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: NatGateway
        spec:
          forProvider:
            region: eu-north-1
            allocationIdRef:
              name: nat-eip
            subnetIdRef:
              name: public-subnet-1
      dependsOn:
        - nat-eip
        - public-subnet-1
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    # Private Subnet 1
    - name: private-subnet-1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Subnet
        spec:
          forProvider:
            region: eu-north-1
            availabilityZone: eu-north-1a
            cidrBlock: 10.0.64.0/19
            vpcIdRef:
              name: vpc
            tags:
              - key: Name
                value: PrivateSubnet
      dependsOn:
        - vpc
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region

    # Private Route Table 1
    - name: private-route-table-1
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: eu-north-1
            vpcIdRef:
              name: vpc
            routes:
              - cidrBlock: 0.0.0.0/0
                natGatewayIdRef:
                  name: nat-gateway
            tags:
              - key: Name
                value: PrivateSubnet
      dependsOn:
        - nat-gateway
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region 