apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc.aws.platform.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: aws.platform.example.org/v1alpha1
    kind: XVPC
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            # VPC
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: VPC
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: vpc
              labels:
                provider: aws
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                cidrBlock: {{ .observed.composite.resource.spec.parameters.cidrBlock }}
                enableDnsSupport: true
                enableDnsHostnames: true

            ---
            # Internet Gateway
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: InternetGateway
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: internet-gateway
              labels:
                provider: aws
                gateway-type: internet
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                vpcIdSelector:
                  matchControllerRef: true

            ---
            # NAT Gateway
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: NATGateway
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: nat-gateway
              labels:
                provider: aws
                gateway-type: nat
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                allocationIdSelector:
                  matchLabels:
                    eip-type: nat
                subnetIdSelector:
                  matchLabels:
                    subnet-type: private

            ---
            # NAT EIP
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: EIP
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: nat-eip
              labels:
                provider: aws
                eip-type: nat
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                domain: vpc
              managementPolicies:
                - "*"

            ---
            # Public Subnets
            {{- $azs := list "us-east-1a" "us-east-1b" "us-east-1c" }}
            {{- range $i, $az := $azs }}
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Subnet
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: public-subnet-{{ add $i 1 }}
              labels:
                provider: aws
                subnet-type: public
                subnet-name: public-subnet-{{ add $i 1 }}
            spec:
              forProvider:
                region: {{ $.observed.composite.resource.spec.parameters.region }}
                cidrBlock: 10.0.{{ add $i 1 }}.0/24
                availabilityZone: {{ $az }}
                mapPublicIpOnLaunch: true
                vpcIdSelector:
                  matchControllerRef: true
            ---
            {{- end }}

            ---
            # Private Subnets
            {{- $privateAzs := list "us-east-1a" "us-east-1b" "us-east-1c" }}
            {{- range $i, $az := $privateAzs }}
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Subnet
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: private-subnet-{{ add $i 1 }}
              labels:
                provider: aws
                subnet-type: private
                subnet-name: private-subnet-{{ add $i 1 }}
            spec:
              forProvider:
                region: {{ $.observed.composite.resource.spec.parameters.region }}
                cidrBlock: 10.0.{{ add $i 10 }}.0/24
                availabilityZone: {{ $az }}
                mapPublicIpOnLaunch: false
                vpcIdSelector:
                  matchControllerRef: true
            ---
            {{- end }}

            ---
            # Public Route Table
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTable
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: public-route-table
              labels:
                provider: aws
                table-type: public
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                vpcIdSelector:
                  matchControllerRef: true

            ---
            # Public Route to Internet Gateway
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Route
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: public-route-igw
              labels:
                provider: aws
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                routeTableIdSelector:
                  matchLabels:
                    table-type: public
                destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchLabels:
                    gateway-type: internet

            ---
            # Public Route Table Associations
            {{- range $i, $az := $azs }}
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTableAssociation
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: public-rt-assoc-{{ add $i 1 }}
              labels:
                provider: aws
            spec:
              forProvider:
                region: {{ $.observed.composite.resource.spec.parameters.region }}
                subnetIdSelector:
                  matchLabels:
                    subnet-name: public-subnet-{{ add $i 1 }}
                routeTableIdSelector:
                  matchLabels:
                    table-type: public
            ---
            {{- end }}

            ---
            # Private Route Table
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTable
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: private-route-table
              labels:
                provider: aws
                table-type: private
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                vpcIdSelector:
                  matchControllerRef: true

            ---
            # Private Route to NAT Gateway
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Route
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: private-route-nat
              labels:
                provider: aws
            spec:
              forProvider:
                region: {{ .observed.composite.resource.spec.parameters.region }}
                routeTableIdSelector:
                  matchLabels:
                    table-type: private
                destinationCidrBlock: 0.0.0.0/0
                natGatewayIdSelector:
                  matchLabels:
                    gateway-type: nat

            ---
            # Private Route Table Associations
            {{- range $i, $az := $privateAzs }}
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTableAssociation
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: private-rt-assoc-{{ add $i 1 }}
              labels:
                provider: aws
            spec:
              forProvider:
                region: {{ $.observed.composite.resource.spec.parameters.region }}
                subnetIdSelector:
                  matchLabels:
                    subnet-name: private-subnet-{{ add $i 1 }}
                routeTableIdSelector:
                  matchLabels:
                    table-type: private
            ---
            {{- end }}

    - step: auto-ready
      functionRef:
        name: function-auto-ready